site_name: Art of Hosting
site_url: https://art-of-hosting.github.io/
theme:
  name: material
  language: es
nav:
  - index.md
  - elartedeanfitrionar.md
  - sobreeldialogo.md
  - elartedecosechar.md
  - fundamentosdediseño.md
  - practicas.md
  - recursos-complementarios.md
